### PR TITLE
quote table name

### PR DESCRIPTION
**Pull request by calvinmetcalf**
possible fix for #10, can test tommorow

### CODE REVIEW

**Comment by sethfitz** [comment]
https://github.com/segmentio/pg-escape is nice for these types of things, even if CartoDB isn't strictly a Postgres database.

**Comment by calvinmetcalf** [comment]
it actually is literally postgres 9.3 so that will actually come in pretty handy, it's only coming up because 
- I'm using a raw string, had I been using the knex like api it would have all been quoted nicely
- it looks like a dash is legal for a column name in cartodb but not for a table name so it isn't being sanatized out.

**Comment by sethfitz** [comment]
It looks legal when quoted:

```
# create table "foo-1" as select 1;
SELECT 1
```

Ah, knex bypassing, makes sense.

**Comment by calvinmetcalf** [comment]
actually as it turns out a dash is fine in postgres but NOT in cartodb which will change it to have an underscopre

**Comment by calvinmetcalf** [comment]
which as it turns out is also the same for columns

**Pull request merged**
